### ISSUE TITLE
How does one use/install this?

### ISSUE THREAD

**Issue by slikts** [cescue/language-autohotkey#10]
Is this package in atom.io/packages? It doesn't appear to be. Is there some other way to install it? Would be nice to have a note about installing/usage in the readme.

**Comment by cescue** [comment]
Right now, the easiest way to install it is to download the atom.io package by nshakin, and replace `package.json` and `autohotkey.cson` with the files in this repo.

I'm working on a solution to publishing an atom.io package, but I'd like to avoid package clutter (e.g. language-autohotkey-2, language-autohotkey-3, etc).  Related issue: #4.

**Comment by slikts** [comment]
This info really belongs in the readme, even if it's a temporary solution.

**Comment by cescue** [comment]
Readme has been updated for now.
