### ISSUE TITLE
"Editor: Toggle Line Comments" toggles block comment instead of line comment

### ISSUE THREAD

**Issue by HactarCE** [cescue/language-autohotkey#3]
`Editor: Toggle Line Comments` toggles block comment. (It should toggle line comment `;`.)

~~Block comments are only highlighted at the very start of a line (should be allowed at any point in a line). This applies to both the start `/*` and end `*/` of block comments.~~ This is intended behavior.

**Comment by cescue** [comment]
Fixed in 1.0.1. Thanks!
