### ISSUE TITLE
Percents not always matched

### ISSUE THREAD

**Issue by jinglesthula** [cescue/language-autohotkey#4]
Here are a couple examples where the percent signs aren't always colored correctly.

On this one, only the `%` characters surrounding `MouseY` are colored correctly.

`foo := { "color": %color%, "MouseX": %MouseX%, "MouseY": %MouseY% }`

On this one the opening one before `color` matches the closing one after `MouseY` and the others are treated like part of a variable name.

`SplashTextOn, , , color: %color% x: %MouseX% y: %MouseY%`

**Comment by cescue** [comment]
Can you upload a screenshot of what you're seeing in your editor?

**Comment by jinglesthula** [comment]
I have to apologize - I've edited the file since and am not able to reproduce the issue.  I'm now thinking I must have had a syntax error somewhere earlier on in the file I was editing that threw it off.
