### ISSUE TITLE
Fix for multiline comments

### ISSUE THREAD

**Issue by cescue** [cescue/language-autohotkey#5]
Per the AutoHotkey documentation:

>In addition, the /* and \*/ symbols can be used to comment out an entire section, **but only if the symbols appear at the beginning of a line**

Emphasis mine - currently, the `/*` and `*/` comment delimiters will work regardless of their position on the line.

**Comment by vanillaSprinkles** [comment]
If I understood correctly: https://github.com/cescue/language-autohotkey/pull/6
