### ISSUE TITLE
semi-colon in hotstring causes incorrect mark as comment

### ISSUE THREAD

**Issue by awfki** [cescue/language-autohotkey#7]
First, thank you for making this for Atom.  I haven't used Windows for years but I'm back now and that means AutoHotKey and I was so happy to find this syntax highlighter. But... I often use semi-colons in hotstrings and right now they're being marked as comments.

For example:
`::;tst::this is not a comment`

I think I should be changing this line in autohotkey.cson but nothing I tried seemed to make any difference.  
`    match: "((;).*)"`

Just for the record these are some of my attempts.
`    match: "\b((;).*)"`
`    match: "[^:]((;).*)"`
`    match: "(?:^|\W)((;).*)"`

None of that changed anything.  Can you point me in the right direction?
Thank you

**Comment by cescue** [comment]
Thanks for creating the issue! I don't work with AHK often, so I usually find myself relying on others to tell me when something is busted 😬 .

I think the easiest way to go about this would be to add a rule that supersedes the comment pattern. Something like this:

```coffeescript
  # Place this somewhere after the inline comment definition
  {
    comment: "hotstrings"
    name: ".entity.name.function.ahk"
    match: "^::.+::"
  }
```
Does this behave like you'd expect it to?

**Comment by awfki** [comment]
No, but I'll warn you that I have very little idea what I'm doing. :)  

I put immediately after the comment like so.
```  {
    comment: "inline comments"
    captures:
      "1":
        name: ".comment.line.ahk"
      "2":
        name: ".punctuation.definition.semi-colon.comment.ahk"
    match: "((;).*)"
  }
  {
    comment: "hotstrings"
    name: ".entity.name.function.ahk"
    match: "^::.+::"
  }
```

I then disabled the language, reloaded the sample.ahk file (with my addition) and enabled the language.  It promptly marked it as a comment.

**Comment by cescue** [comment]
I don't believe toggling the language will reload the grammar.

Try a hard-refresh of the editor after changing the grammar - either <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>f5</kbd> or simply restart the editor.

**Comment by awfki** [comment]
You were right about it not reloading the grammar.  ctrl+shift+f5 worked.
I modified your hotstring definition slightly to include strings starting with `:*:`.

```  {
    comment: "hotstrings"
    name: ".entity.name.function.ahk"
    match: "^:\*?:.+::"
  }
```

Thank you very much for your help, and for making the language package!
